services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/internal/storage:/app/storage

  frontend:
    environment:
    - VITE_API_URL=http://backend:8000/v1  # Перезапишет .env
    volumes:
    - ./frontend:/app  
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend